### ISSUE TITLE
Add OpsGenie as Happy Hour Sponsor

### ISSUE THREAD

**Issue by nathenharvey** [DevOpsDaysDC/planning#102]
Happy Hour Sponsors should be listed before Platinum Sponsors, after location sponsor.

![opsgenie-logo-horizontal](https://cloud.githubusercontent.com/assets/16093/15575984/8a5f4656-2323-11e6-8d0c-9835bbb9dedd.png)

**Comment by markcornick** [comment]
https://github.com/devopsdays/devopsdays-web/pull/468
