### ISSUE TITLE
Finalize Volunteer List

### ISSUE THREAD

**Issue by nathenharvey** [DevOpsDaysDC/planning#107]
Let's get the list finalized and notices out to all volunteers.

**Comment by mbarbine** [comment]
where is this list located?

**Comment by radiocats** [comment]
The initial list is here:  https://docs.google.com/document/d/1rPk7PQFOuqE13zz7iSb3AZjKgjaK8nvRNjpdIaJdJ8o/edit?ts=573bbc91#
Michael, can we please put Alicia down for registration again?  She did a fantastic job last year.
 

    On Tuesday, May 31, 2016 11:13 PM, Michael Barbine <notifications@github.com> wrote:
 

 where is this list located? —
