### ISSUE TITLE
Sponsor Updates

### ISSUE THREAD

**Issue by nathenharvey** [DevOpsDaysDC/planning#108]
* When can they set-up on Tuesday?
  * 3PM - 5PM
* Where is their table (Platinum and Gold only)?
* When is their one-minute pitch (Platinum only)?
  * Remind the sponsors that one-minute means one minute.

**Comment by nathenharvey** [comment]
@jasonNetuitive I think this is complete, right?

**Comment by jasonNetuitive** [comment]
yes, I sent out a note this morning to all the sponsors
