### ISSUE TITLE
Chimes?

### ISSUE THREAD

**Issue by nathenharvey** [DevOpsDaysDC/planning#111]
Have you been able to source chimes?

**Comment by mbarbine** [comment]
https://www.youtube.com/watch?v=sTHI6CsLwxk

**Comment by nathenharvey** [comment]
[Here are some from Amazon](http://www.amazon.com/Woodstock-Percussion-ZENERGY3-Zenergy-Instrument/dp/B0000775FZ/ref=sr_1_2?s=musical-instruments&ie=UTF8&qid=1464707530&sr=1-2&keywords=chimes)

**Comment by radiocats** [comment]
I was hesitant about the amazon chimes. I like these but wasn't crazy about the price:
Ross Dinner Chimes

  
|  
|   
|   
|   |    |

   |

  |
|  
|   |  
Ross Dinner Chimes
 Ross Dinner Chimes work well for calling guests to dinner or teaching young musicians. Ross dinner chimes are t...  |   |

  |

  |

 

 

    On Tuesday, May 31, 2016 11:12 AM, Nathen Harvey <notifications@github.com> wrote:
 

 Here are some from Amazon—

**Comment by nathenharvey** [comment]
ordered for delivery to my attention at the Westin on Tuesday.
