### ISSUE TITLE
Happy hour slide deck

### ISSUE THREAD

**Issue by nathenharvey** [DevOpsDaysDC/planning#112]

**Comment by mbarbine** [comment]
@nathenharvey - Would you like me to draft this up and give it to you for a final spin?

**Comment by nathenharvey** [comment]
yes, that'd be awesome.  We need to feature our two happy hour sponsors, maybe a schedule for the evening, a reminder about the Thursday start time, and, of course, the DevOpsDays DC logo. 

I'll reassign this to you @mbarbine

**Comment by nathenharvey** [comment]
@mbarbine check out the [slide deck here](https://github.com/DevOpsDaysDC/planning/tree/master/2016-slides).  It has all the sponsors so you can just pull the two happy hour sponsors out.

**Comment by nathenharvey** [comment]
@mbarbine any progress on this?

**Comment by mbarbine** [comment]
Im working on it. Ill have over soon.




Respectfully,
Michael Barbine
Excella Consulting,  Senior Consultant
michael.barbine@excella.com / 540-671-1261 / excella.com



On Mon, Jun 6, 2016 at 9:54 PM -0400, "Nathen Harvey" <notifications@github.com<mailto:notifications@github.com>> wrote:


@mbarbine<https://github.com/mbarbine> any progress on this?

-
