### ISSUE TITLE
sponsor slide deck

### ISSUE THREAD

**Issue by nathenharvey** [DevOpsDaysDC/planning#114]
Need a deck that includes each sponsor and their twitter handles.

**Comment by nathenharvey** [comment]
I've started a deck here - https://github.com/DevOpsDaysDC/planning/tree/master/2016-slides

@markcornick @jasonNetuitive there are a couple sponsors that are missing twitter handles and a bunch that we could use better logos for.  Do you have any of these readily available?  Mind updating the pptx?

Need better logos for:
* Pivotal
* CloudPassage
* CaptialOne
* eGlobalTech
* SolarWinds
* CSRA
* ThoughtWorks
* GitHub
* DLT
* OmniTI
* ASPE
* Sauce Labs
* Karsun
* Harmonia
* Evident.io
* CloudBees
* JHC
* STSI
* PhishMe
* SolidFire
* Fearless
* AIS


Need Twitter handles for the following (I've already asked)
* Harmonia
* Halvik

**Comment by markcornick** [comment]
I don't have anything on hand beyond what's in the devopsdays-web repo. As you've seen, some of those are 100x100px squares carried over from the old webby repo, and the newer ones are 200x200px. Neither is really ideal.

**Comment by nathenharvey** [comment]
OK, I've reached out to all the sponsors giving them a chance to review and send back updated logos.

**Comment by jasonNetuitive** [comment]
Thanks man.  I can just pull the logos from google if we don't get responses.  That was basically my plan with this task.

Sent from my iPhone

On Jun 1, 2016, at 11:28 PM, Nathen Harvey <notifications@github.com<mailto:notifications@github.com>> wrote:


OK, I've reached out to all the sponsors giving them a chance to review and send back updated logos.

-

**Comment by nathenharvey** [comment]
got a bunch of logo updates, grabbed some others.  Marking this as closed.
