### ISSUE TITLE
Pre-event email to attendees

### ISSUE THREAD

**Issue by nathenharvey** [DevOpsDaysDC/planning#117]
Hi {{ first_name }}!

DevOpsDays DC is next week!  We are so happy that you'll be part of our sold out DevOpsDays event.

**Logistics**

* June 8-9, 2016
* US Patent and Trademark Office (USPTO), Madison Building, 600 Dulany St., Alexandria, VA  22314
* The USPTO is a non-smoking campus
* [Directions to the Madison Building](http://www.uspto.gov/page/directions-madison-buildings-east-west-600-dulany-street-alexandria-va) are available on the USPTO site.
  * The King Street Metro station in Alexandria (yellow or blue line) is a short walk from the Madison Building.
    * Please remember that [Metro Rail is running trains on the Orange and Silver lines along a single track between East Falls Church and Ballston](http://www.wmata.com/rider_tools/metro_service_status/advisories.cfm?AID=5578), plan accordingly.
  * When entering the Madison building from Dulany Street, please head to the lower atrium for registration.  You may use the stairs at the opposite end of the building or the elevator which is in the far left-hand corner.
  * When entering from Eisenhower Avenue, you will enter into the lower atrium and the registration tables will be on your left and right.

**Dress Code**

Some people will come in suits, many will be in t-shirts.  Dress for comfort and as suits your personal style.

**WiFi**

The USPTO has made public WiFi available to all DevOpsDays DC attendees.  Please be considerate of other attendees and be a good consumer of the WiFi.  DevOpsDays are about connecting with others in our industry in person.  If you are on-call during DevOpsDays DC, we recommend coming prepared with alternate connectivity solutions such as a mifi puck.

**Schedule**

DevOpsDays events are a mix of keynote presentations, ignite talks, and open spaces.  You will find the [schedule for DevOpsDays DC online](http://devopsdaysdc2016.busyconf.com/schedule).   Bringing local DevOps representatives to you was one of our goals and you'll notice that almost every one of our presenters works within 100 miles of DC.

**A note on lunch** - We are a big gathering utilizing some of the common areas of the USPTO office space.  As a courtesy to our hosts and those not attending the conference, we will be serving lunch at 1:00PM each day.  Please plan accordingly by having a nice hearty breakfast or by packing some snacks to get you through the morning.

**Wednesday, June 8** includes keynotes from [Mark A. Schwartz](https://twitter.com/schwartz_cio), [David Copeland](https://twitter.com/davetron5000), [Tapabrata Pal](https://twitter.com/TopoPal), [Trent Hone](https://twitter.com/Honer_CUT), and [Laura Barton](http://twitter.com/laurabartondev).  We will then have some ignite presentations, create a schedule for our open space discussions, and then break for lunch.  After lunch we will have a few more ignite talks before going into our open space discussions.  Wednesday night includes a DevOpsDays DC Happy Hour at the [Carlyle Club](http://thecarlyleclub.com/) and will feature live music from [Detached Retina](http://www.detachedretinamusic.com/).

**Thursday, June 9** includes keynotes from [Mike Bland](https://devopsdaysdc2016.busyconf.com/activities/5735546817876e1fce00012a), [Elizabeth (Betsy) Nichols, Ph.D.](https://twitter.com/eantweet), [Simmons Lough](https://devopsdaysdc2016.busyconf.com/activities/5702c05999030eb60c000091), [Mike Nescot](https://twitter.com/mnescot), and [Nick Grace](https://twitter.com/nickgrace).  Keynotes will be followed by more ignite talks and creating our open space schedule. After lunch, we'll have more open space discussions.  The event will close with a live recording of the [DevOpsDays Podcast](https://itunes.apple.com/us/podcast/devops-days-podcast/id1035163116?mt=2). 

**Code of Conduct**

We value the participation of each member of the community and want all attendees to have an enjoyable and fulfilling experience. Accordingly, all attendees, speakers, sponsors, and staff are expected to show respect and courtesy to other attendees throughout the conference and at all conference events.

Please take a few minutes to read and familiarize yourself with our [Code of Conduct](http://www.devopsdays.org/events/2016-washington-dc/conduct/).

**Refund Policy**

We know things come up and you may no longer be able to attend.  If that's the case, you must let us know no later than **11:59PM EDT Today, Friday, June 3** so that we can refund your ticket.  We will be really sad to miss you at the event but someone on the waiting list will be really happy to take your place.  

**Twitter**

Be sure to follow [@devopsdaysdc](http://twitter.com/devopsdaysdc) and the [#devopsdays](https://twitter.com/search?q=%23devopsdays) hashtags for all the latest updates on DevOpsDays DC.

**Thank you** for being part of this year's DevOpsDays event in our nation's capital!  What questions can we answer for you?

Sincerely,  
Your {{ event.compact_name }} Organizing Committee  
[@devopsdaysdc](http://twitter.con/devopsdaysdc)

-----
#### Platinum &amp; Venue Sponsor
<a href = "http://www.uspto.gov/"><img alt = "uspto" src = "http://devopsdays.org/img/sponsors/uspto.png" height="100px" width="100px"></a>

#### Happy Hour Sponsors
<a href = "http://www.opsgenie.com"><img alt = "opsgenie" src = "http://devopsdays.org/img/sponsors/opsgenie.png" height="100px" width="100px"></a> &nbsp; &nbsp; <a href = "http://www.aol.com"><img alt = "aol" src = "http://devopsdays.org/img/sponsors/aol.png" height="100px" width="100px"></a>

#### Platinum Sponsors
<a href = "http://www.pivotal.io"><img alt = "pivotal" src = "http://devopsdays.org/img/sponsors/pivotal.png" height="100px" width="100px"></a> &nbsp; &nbsp; <a href = "http://www.cloudpassage.com/"><img alt = "cloudpassage" src = "http://devopsdays.org/img/sponsors/cloudpassage.png" height="100px" width="100px"></a> &nbsp; &nbsp; <a href = "http://www.netuitive.com"><img alt = "netuitive" src = "http://devopsdays.org/img/sponsors/netuitive.png" height="100px" width="100px"></a> &nbsp; &nbsp; <a href = "http://www.capitalone.com/"><img alt = "capitalone" src = "http://devopsdays.org/img/sponsors/capitalone.png" height="100px" width="100px"></a>

<a href = "http://www.eglobaltech.com/"><img alt = "eglobaltech" src = "http://devopsdays.org/img/sponsors/eglobaltech.png" height="100px" width="100px"></a> &nbsp; &nbsp; <a href = "http://www.excella.com/"><img alt = "excella" src = "http://devopsdays.org/img/sponsors/excella.png" height="100px" width="100px"></a> &nbsp; &nbsp; <a href = "http://www.solarwinds.com"><img alt = "solarwinds" src = "http://devopsdays.org/img/sponsors/solarwinds.png" height="100px" width="100px"></a> &nbsp; &nbsp; <a href = "http://www.csra.com/"><img alt = "csra" src = "http://devopsdays.org/img/sponsors/csra.png" height="100px" width="100px"></a>

<a href = "http://www.docker.com/"><img alt = "docker" src = "http://devopsdays.org/img/sponsors/docker.png" height="100px" width="100px"></a> &nbsp; &nbsp; <a href = "http://chef.io"><img alt = "chef" src = "http://devopsdays.org/img/sponsors/chef.png" height="100px" width="100px"></a> &nbsp; &nbsp; <a href = "https://www.thoughtworks.com/products"><img alt = "thoughtworks-products" src = "http://devopsdays.org/img/sponsors/thoughtworks-products.png" height="100px" width="100px"></a> &nbsp; &nbsp; <a href = "http://www.pagerduty.com/"><img alt = "pagerduty" src = "http://devopsdays.org/img/sponsors/pagerduty.png" height="100px" width="100px"></a> 

<a href = "http://www.github.com"><img alt = "github" src = "http://devopsdays.org/img/sponsors/github.png" height="100px" width="100px"></a> &nbsp; &nbsp; <a href = "http://www.customink.com/"><img alt = "customink" src = "http://devopsdays.org/img/sponsors/customink.png" height="100px" width="100px"></a> &nbsp; &nbsp; <a href = "https://www.redhat.com"><img alt = "redhat" src = "http://devopsdays.org/img/sponsors/redhat.png" height="100px" width="100px"></a> &nbsp; &nbsp; <a href = "http://www.ansible.com/"><img alt = "ansible" src = "http://devopsdays.org/img/sponsors/ansible.png" height="100px" width="100px"></a>

<a href = "http://www.dlt.com/"><img alt = "dlt" src = "http://devopsdays.org/img/sponsors/dlt.png" height="100px" width="100px"></a> &nbsp; &nbsp; <a href = "http://www.omniti.com/"><img alt = "omniti" src = "http://devopsdays.org/img/sponsors/omniti.png" height="100px" width="100px"></a> &nbsp; &nbsp; <a href = "http://www.aspetraining.com"><img alt = "aspe" src = "http://devopsdays.org/img/sponsors/aspe.png" height="100px" width="100px"></a> &nbsp; &nbsp; <a href = "https://saucelabs.com"><img alt = "saucelabs" src = "http://devopsdays.org/img/sponsors/saucelabs.png" height="100px" width="100px"></a>

#### Gold Sponsors
<a href = "http://www.infozen.com/"><img alt = "infozen" src = "http://devopsdays.org/img/sponsors/infozen.png" height="100px" width="100px"></a> &nbsp; &nbsp; <a href = "http://www.comcast.com/"><img alt = "comcast" src = "http://devopsdays.org/img/sponsors/comcast.png" height="100px" width="100px"></a> &nbsp; &nbsp; <a href = "http://www.karsun-llc.com/"><img alt = "karsun" src = "http://devopsdays.org/img/sponsors/karsun.png" height="100px" width="100px"></a> &nbsp; &nbsp; <a href = "http://www.harmonia.com/"><img alt = "harmonia" src = "http://devopsdays.org/img/sponsors/harmonia.png" height="100px" width="100px"></a>

<a href = "http://evident.io/"><img alt = "evident" src = "http://devopsdays.org/img/sponsors/evident.png" height="100px" width="100px"></a> &nbsp; &nbsp; <a href = "http://www.victorops.com"><img alt = "victorops" src = "http://devopsdays.org/img/sponsors/victorops.png" height="100px" width="100px"></a> &nbsp; &nbsp; <a href = "http://www.cloudbees.com/"><img alt = "cloudbees" src = "http://devopsdays.org/img/sponsors/cloudbees.png" height="100px" width="100px"></a> &nbsp; &nbsp; <a href = "http://www.fanniemae.com/"><img alt = "fanniemae" src = "http://devopsdays.org/img/sponsors/fanniemae.png" height="100px" width="100px"></a> &nbsp; &nbsp;

**Comment by atkraft** [comment]
Should we mention Metro's Continuous Single Tracking on the Orange & Silver Lines from Ballston to East Falls Church?  Most locals are well aware of this, there may be a few out of town folks who have not heard.

http://www.wmata.com/rider_tools/metro_service_status/advisories.cfm?AID=5578

**Comment by nathenharvey** [comment]
good call @atkraft!  I've added another line to the message:


* Please remember that [Metro Rail is running trains on the Orange and Silver lines along a single track between East Falls Church and Ballston](http://www.wmata.com/rider_tools/metro_service_status/advisories.cfm?AID=5578), plan accordingly.

**Comment by nathenharvey** [comment]
sent!
