### ISSUE TITLE
Day before email

### ISSUE THREAD

**Issue by nathenharvey** [DevOpsDaysDC/planning#119]
Hi {{ first_name }}!

DevOpsDays DC starts tomorrow!  We are so happy that you'll be part of our sold out DevOpsDays event.

Registration opens at 8:00AM.  The conference kicks off at 9:00AM.  Coffee and a light breakfast will be served during the registration hours.

**Location**

* USPTO, Madison Building, 600 Dulany St., Alexandria, VA  22314
* [Directions to the Madison Building](http://www.uspto.gov/page/directions-madison-buildings-east-west-600-dulany-street-alexandria-va) are available on the USPTO site.  The King Street Metro station in Alexandria (yellow or blue line) is very close.
  * Please remember that [Metro Rail is running trains on the Orange and Silver lines along a single track between East Falls Church and Ballston](http://www.wmata.com/rider_tools/metro_service_status/advisories.cfm?AID=5578), plan accordingly.

**Dress Code**

Some people will come in suits, many will be in t-shirts.  Dress for comfort and as suits your personal style.

**Caffeine and Food**

* Coffee will be available throughout the day.
* A light breakfast and morning snack will be served.
* **Lunch is at 1PM**.
* Light snacks will be offered in the afternoon.

**WiFi**

Public WiFi will be available. If you are on-call during DevOpsDays DC, we recommend coming prepared with alternate connectivity solutions such as a mifi puck.  The SSID is "Public", no authentication will be required.

**Notes**

We've set-up a place for the community to take shared notes during the sessions and open spaces.  Everyone is invited to participate by creating and contributing to the [DevOpsDays DC Etherpad](http://e.devopsdaysdc.org).

**Important Links**

* [Schedule](http://devopsdaysdc2016.busyconf.com/schedule)
* [Code of Conduct](http://www.devopsdays.org/events/2016-washington-dc/conduct/)
* [Etherpad for notes](http://e.devopsdaysdc.org)
* Twitter
  * [@devopsdaysdc](http://twitter.com/devopsdaysdc)
  * [#devopsdays](https://twitter.com/search?q=%23devopsdays)
  
**Thank you** for being part of this year's DevOpsDays event in our nation's capital!  What questions can we answer for you?

----
#### Platinum &amp; Venue Sponsor
<a href = "http://www.uspto.gov/"><img alt = "uspto" src = "http://devopsdays.org/img/sponsors/uspto.png" height="100px" width="100px"></a>

#### Happy Hour Sponsors
<a href = "http://www.opsgenie.com"><img alt = "opsgenie" src = "http://devopsdays.org/img/sponsors/opsgenie.png" height="100px" width="100px"></a> &nbsp; &nbsp; <a href = "http://www.aol.com"><img alt = "aol" src = "http://devopsdays.org/img/sponsors/aol.png" height="100px" width="100px"></a>

#### Platinum Sponsors
<a href = "http://www.pivotal.io"><img alt = "pivotal" src = "http://devopsdays.org/img/sponsors/pivotal.png" height="100px" width="100px"></a> &nbsp; &nbsp; <a href = "http://www.cloudpassage.com/"><img alt = "cloudpassage" src = "http://devopsdays.org/img/sponsors/cloudpassage.png" height="100px" width="100px"></a> &nbsp; &nbsp; <a href = "http://www.netuitive.com"><img alt = "netuitive" src = "http://devopsdays.org/img/sponsors/netuitive.png" height="100px" width="100px"></a> &nbsp; &nbsp; <a href = "http://www.capitalone.com/"><img alt = "capitalone" src = "http://devopsdays.org/img/sponsors/capitalone.png" height="100px" width="100px"></a>

<a href = "http://www.eglobaltech.com/"><img alt = "eglobaltech" src = "http://devopsdays.org/img/sponsors/eglobaltech.png" height="100px" width="100px"></a> &nbsp; &nbsp; <a href = "http://www.excella.com/"><img alt = "excella" src = "http://devopsdays.org/img/sponsors/excella.png" height="100px" width="100px"></a> &nbsp; &nbsp; <a href = "http://www.solarwinds.com"><img alt = "solarwinds" src = "http://devopsdays.org/img/sponsors/solarwinds.png" height="100px" width="100px"></a> &nbsp; &nbsp; <a href = "http://www.csra.com/"><img alt = "csra" src = "http://devopsdays.org/img/sponsors/csra.png" height="100px" width="100px"></a>

<a href = "http://www.docker.com/"><img alt = "docker" src = "http://devopsdays.org/img/sponsors/docker.png" height="100px" width="100px"></a> &nbsp; &nbsp; <a href = "http://chef.io"><img alt = "chef" src = "http://devopsdays.org/img/sponsors/chef.png" height="100px" width="100px"></a> &nbsp; &nbsp; <a href = "https://www.thoughtworks.com/products"><img alt = "thoughtworks-products" src = "http://devopsdays.org/img/sponsors/thoughtworks-products.png" height="100px" width="100px"></a> &nbsp; &nbsp; <a href = "http://www.pagerduty.com/"><img alt = "pagerduty" src = "http://devopsdays.org/img/sponsors/pagerduty.png" height="100px" width="100px"></a> 

<a href = "http://www.github.com"><img alt = "github" src = "http://devopsdays.org/img/sponsors/github.png" height="100px" width="100px"></a> &nbsp; &nbsp; <a href = "http://www.customink.com/"><img alt = "customink" src = "http://devopsdays.org/img/sponsors/customink.png" height="100px" width="100px"></a> &nbsp; &nbsp; <a href = "https://www.redhat.com"><img alt = "redhat" src = "http://devopsdays.org/img/sponsors/redhat.png" height="100px" width="100px"></a> &nbsp; &nbsp; <a href = "http://www.ansible.com/"><img alt = "ansible" src = "http://devopsdays.org/img/sponsors/ansible.png" height="100px" width="100px"></a>

<a href = "http://www.dlt.com/"><img alt = "dlt" src = "http://devopsdays.org/img/sponsors/dlt.png" height="100px" width="100px"></a> &nbsp; &nbsp; <a href = "http://www.omniti.com/"><img alt = "omniti" src = "http://devopsdays.org/img/sponsors/omniti.png" height="100px" width="100px"></a> &nbsp; &nbsp; <a href = "http://www.aspetraining.com"><img alt = "aspe" src = "http://devopsdays.org/img/sponsors/aspe.png" height="100px" width="100px"></a> &nbsp; &nbsp; <a href = "https://saucelabs.com"><img alt = "saucelabs" src = "http://devopsdays.org/img/sponsors/saucelabs.png" height="100px" width="100px"></a>

#### Gold Sponsors
<a href = "http://www.infozen.com/"><img alt = "infozen" src = "http://devopsdays.org/img/sponsors/infozen.png" height="100px" width="100px"></a> &nbsp; &nbsp; <a href = "http://www.comcast.com/"><img alt = "comcast" src = "http://devopsdays.org/img/sponsors/comcast.png" height="100px" width="100px"></a> &nbsp; &nbsp; <a href = "http://www.karsun-llc.com/"><img alt = "karsun" src = "http://devopsdays.org/img/sponsors/karsun.png" height="100px" width="100px"></a> &nbsp; &nbsp; <a href = "http://www.harmonia.com/"><img alt = "harmonia" src = "http://devopsdays.org/img/sponsors/harmonia.png" height="100px" width="100px"></a>

<a href = "http://evident.io/"><img alt = "evident" src = "http://devopsdays.org/img/sponsors/evident.png" height="100px" width="100px"></a> &nbsp; &nbsp; <a href = "http://www.victorops.com"><img alt = "victorops" src = "http://devopsdays.org/img/sponsors/victorops.png" height="100px" width="100px"></a> &nbsp; &nbsp; <a href = "http://www.cloudbees.com/"><img alt = "cloudbees" src = "http://devopsdays.org/img/sponsors/cloudbees.png" height="100px" width="100px"></a> &nbsp; &nbsp; <a href = "http://www.fanniemae.com/"><img alt = "fanniemae" src = "http://devopsdays.org/img/sponsors/fanniemae.png" height="100px" width="100px"></a> &nbsp; &nbsp;

---
# Who is coming to DevOpsDays DC?  

<img src="http://www.devopsdays.org/events/2016-washington-dc/DevOpsDaysDC_2016_attendees.png" />

**Comment by atkraft** [comment]
deleted "inaugural" in the first line

**Comment by atkraft** [comment]
Could add 2016 or second where "inaugural" was if that sounds best to you; or just leave as is.

**Comment by nathenharvey** [comment]
How about this:

> We are so happy that you'll be part of our sold out DevOpsDays event.

**Comment by atkraft** [comment]
Sounds good

**Comment by atkraft** [comment]
The links for "DevOpsDays DC Etherpad" and "Etherpad for notes" are not working.

**Comment by nathenharvey** [comment]
thanks, e.devopsdaysdc.org should be working again now, I launched an new etherpad site for us.

**Comment by nathenharvey** [comment]
Delivered to 521 recipients
