### ISSUE TITLE
Email to wait listed people

### ISSUE THREAD

**Issue by nathenharvey** [DevOpsDaysDC/planning#122]
Hello!

I am sorry to inform you that next week's [DevOpsDays DC](http://www.devopsdays.org/events/2016-washington-dc/welcome/) is completely sold out and we will not be able to open any additional tickets.

I know this is disappointing and really wish we had capacity for everyone to attend.

We will be streaming the keynotes and ignite talks live to the DevOpsDays DC website on Wednesday and Thursday, perhaps you could catch the live stream.

After the conference, we will make slides, videos, and audio of each of the presentations available.

There is a small chance that we may be able to open up a limited number of spaces for Thursday-only.  An email will be sent out by 5PM on Wednesday to let you know.

We are planning to host another DevOpsDays DC in 2017 and hope you will join us then.  In the meantime, might we suggest you look into attending either [DevOpsDays Baltimore](http://www.devopsdays.org/events/2016-baltimore/welcome/), [DevOpsDays New York](http://www.devopsdays.org/events/2016-newyork/welcome/), [DevOpsDays Raleigh](http://www.devopsdays.org/events/2016-raleigh/welcome/), and/or [DevOpsDays Philadelphia](http://www.devopsdays.org/events/2016-philadelphia/welcome/) later this year?

Thank you!
The DevOpsDays DC Organizing Committee 
@devopsdaysdc

**Comment by atkraft** [comment]
Looks good; suggesting the other DevOpsDays is a good idea.

**Comment by xzilla** [comment]
+1 LGTM

**Comment by nathenharvey** [comment]
sent
