### ISSUE TITLE
Registration Page

### ISSUE THREAD

**Issue by markcornick** [DevOpsDaysDC/planning#19]
Create registration page with link to BusyConf and explanatory information. Depending on how BusyConf works, this could be a link directly to them, or our own page.

**Comment by gallimorej** [comment]
The link to the registration page for attendees should be https://devopsdaysdc2015.busyconf.com/bookings/new. Given how the other DevOpsDays events are set up (look at Denver and New York), I think it's OK to link right to BusyConf.

**Comment by markcornick** [comment]
Great! Are you ready to have this go live now (over this weekend, probably) or should I wait until you say go?

**Comment by gallimorej** [comment]
Let's wait until Monday to go live with it just in case other eyes see any issues with it between now and then. I tested it out -- but I was also the "developer" :-)
