### ISSUE TITLE
Add to lanyrd

### ISSUE THREAD

**Issue by nathenharvey** [DevOpsDaysDC/planning#27]

**Comment by markcornick** [comment]
Already there: http://lanyrd.com/2015/devopsdaysdc/ Needs to be claimed; @nathenharvey do you want to claim it?

**Comment by nathenharvey** [comment]
I've claimed it and my claim is under review.  

I also added some additional details but feel free to flesh it out a bit more.

**Comment by nathenharvey** [comment]
Good news! Your claim has been approved.
Hi Nathen Harvey, 
You recently submitted a claim to take ownership of the following event on Lanyrd:

DevOpsDays DC, 11th-12th June 2015

Good news! Your claim has been approved. Now you can:

Embed the event schedule and list of attendees in your own website
Add full length bios and upload photos for each of your speakers
Set up rooms at your venue and use them to create a grid for your schedule
Don't forget to try out our iPad, iPhone and Mobile Web apps, which make it super-easy to provide mobile versions of your event schedule, speaker and attendee lists:

http://lanyrd.com/mobile/ (or install Lanyrd from the App Store)
Our apps work offline, so your attendees will have access to the information they need even if they don't have a reliable data connection. Learn more about our apps in this slide deck.

Got any questions? If so, please just drop us a line by replying to this email.


Best regards, 
The Lanyrd team 

Are these emails helpful? Mail us at support@lanyrd.com and let us know how we can improve them! 
You can unsubscribe from these e-mails or change your preferences at any time.

**Comment by nathenharvey** [comment]
Updated the page.  Calling this "done"
