### ISSUE TITLE
register volunteers

### ISSUE THREAD

**Issue by nathenharvey** [DevOpsDaysDC/planning#35]

**Comment by owdd** [comment]
I would be glad to help with registration if needed.  It looks like there is still a need according to the google doc.

**Comment by radiocats** [comment]
Thank you, Derek.  I have added you.
 


     On Friday, May 22, 2015 11:03 AM, Derek Daczewitz <notifications@github.com> wrote:
   

 I would be glad to help with registration if needed. It looks like there is still a need according to the google doc.—
