### ISSUE TITLE
Generate and send sponsor welcome kit

### ISSUE THREAD

**Issue by nathenharvey** [DevOpsDaysDC/planning#38]
Should include:

* Schedule
* [Floor plan](https://github.com/DevOpsDaysDC/planning/blob/master/floorplan.pdf) with table assignments
* Information about sponsor pitch (for platinum sponsors)
* Code of Conduct
* What else?

**Comment by jasonNetuitive** [comment]
I am sending you this via email.  I don't think we can send it from BusyConf because of the image.

**Comment by jasonNetuitive** [comment]
email sent.  Please review and send

**Comment by nathenharvey** [comment]
Email to sponsors sent!
