### ISSUE TITLE
Staff / Volunteer Contact Cards

### ISSUE THREAD

**Issue by nathenharvey** [DevOpsDaysDC/planning#39]
index sized cards with all staff and volunteer information

**Comment by radiocats** [comment]
My twitter is:  @radiocats and my title is "Manager/Principal Database Administrator".  Thanks.

**Comment by nathenharvey** [comment]
my info is correct, thanks @xzilla

**Comment by radiocats** [comment]
I know this may be too late for printing but Krishna Palati's cell number is 571-236-8861 and title is: "Principal Database Administrator" at FireEye
