### ISSUE TITLE
Speaker Gift bags

### ISSUE THREAD

**Issue by nathenharvey** [DevOpsDaysDC/planning#41]
* Smartwater
* mints
* Advil - 2 personal packs
* Emergen-C
* Hand sanitizer
* Tissues
* Granola or protein bar
* Speaker gift

**Comment by nathenharvey** [comment]
I've ordered etched pint glasses for speakers.

I think a [box of chocolates](http://www.gearhartschocolates.com/16_Piece_Assortment_p/assortment_16.htm) for each speaker would be good, too.  40 of [these](http://www.gearhartschocolates.com/16_Piece_Assortment_p/assortment_16.htm) would be about $1400.

**Comment by nathenharvey** [comment]
The box of chocolates is probably going to push us over budget and we should skip.

**Comment by mbarbine** [comment]
Do we already have bags? like a ... "DevOpsDays DC 2015" burlap sack or do bags need to be purchased along with the items listed?

**Comment by nathenharvey** [comment]
I'm thinking we use simple paper gift bags as getting something custom at this stage will be a bit difficult and isn't currently in the budget.

**Comment by mbarbine** [comment]
I'll take care of this one. I'll get the items listed above. Is there anything else?

**Comment by nathenharvey** [comment]
@mbarbine I think the list above should cover us.  We have a total of 23 speakers.

**Comment by mbarbine** [comment]
23 speaker bags. Got it. I was confused initially on the 40 boxes of chocolate. Something is not adding up here :)
