### ISSUE TITLE
Meetup Sheet for Attendees

### ISSUE THREAD

**Issue by nathenharvey** [DevOpsDaysDC/planning#42]
Would it be worthwhile to have a sheet that lists all relevant / interesting local meetups? 

This would include the name, URL, and maybe one or two sentences about each.

**Comment by mbarbine** [comment]
I have something I shared with my team awhile back. I'll send that out and we can call it a good start. 




Sent on the new Sprint Network from my Samsung Galaxy S®4.

<div>-------- Original message --------</div><div>From: Nathen Harvey <notifications@github.com> </div><div>Date:05/23/2015  7:40 AM  (GMT-05:00) </div><div>To: DevOpsDaysDC/planning <planning@noreply.github.com> </div><div>Subject: [planning] Meetup Sheet for Attendees (#42) </div><div>
</div>Would it be worthwhile to have a sheet that lists all relevant / interesting local meetups?

This would include the name, URL, and maybe one or two sentences about each.

**Comment by nathenharvey** [comment]
@mbarbine have you had any luck finding the one you put together?  How are you document layout skillz?

**Comment by nathenharvey** [comment]
@radiocats offered to help, too.

**Comment by radiocats** [comment]
I will complete this by Friday night.  Is that plenty of time for someone to come behind me and doc skillz my list?

**Comment by mbarbine** [comment]
Sorry this has taken awhile. Yes, I have the doc. 

@radiocats  - Do you want to compare notes? I raised my hand initially for this so I'll do what I said I would do. Be glad to work with you on it though or go behind and review it for you. Let me know.

**Comment by radiocats** [comment]
No worries, Michael.  You got this.  My only suggestions is to make sure it is more DevOps-shaped meetups.  I would assume you would have pointed your team to a good amount of security-oriented meetups as well.  

Happy to compare notes.

**Comment by nathenharvey** [comment]
probably a good idea to just start a wiki page or a markdown file in this repository with the relevant details.  I think the things we'll want to list for each group are:

* name of the group
* url of the group
* next meeting date, location, and topic (if applicable)
* date founded
* number of members

/cc @radiocats @mbarbine

**Comment by nathenharvey** [comment]
I started a [list in the wiki](https://github.com/DevOpsDaysDC/planning/wiki/local_meetups).  Additions welcome and encouraged!

https://github.com/DevOpsDaysDC/planning/wiki/local_meetups

/cc @radiocats @mbarbine @DevOpsDaysDC/owners
