### ISSUE TITLE
VictorOps for event-day communication

### ISSUE THREAD

**Issue by markcornick** [DevOpsDaysDC/planning#46]
I'll work with Jason Hand at VictorOps to get this together.

**Comment by nathenharvey** [comment]
how's this coming?  how will we use it?

**Comment by markcornick** [comment]
Jason gave me access to the devopsdays account on VictorOps. In the past, other events have had a mail alias that forwards into VO and alerts whoever is "on call." We could put the mail alias on the opening slides so we can respond to urgent situations (tech issues, people problems, etc.) I'm thinking we should alert the people who have the MGMT role on our volunteer spreadsheet and whoever seems the most appropriate should respond.

Thoughts @gregelin @gallimorej @jasonNetuitive @grepless? Is this something we still want to do - if people don't think it's necessary, no need to get it set up.

**Comment by gallimorej** [comment]
I'd like to use it if it's not too much of a lift. Setting up the teams would be really important, though. I'd love to have a "Registration" team where we could route issues in that area. Greg and I would obviously be members of that team plus any volunteers who wanted to be -- although that would require a little training and setup.

**Comment by markcornick** [comment]
OK, I'll get some teams set up and get in touch with the MGMT folks to get them set up. Probably happen in the next few days as I'm up in NYC today.

**Comment by radiocats** [comment]
I guess you can put me down as Site MGMT.  I can then be notified and chase down anything location/venue/general shaped when they come up.  

-- Mike
 


     On Thursday, June 4, 2015 3:36 PM, Mark Cornick <notifications@github.com> wrote:
   

 OK, I'll get some teams set up and get in touch with the MGMT folks to get them set up. Probably happen in the next few days as I'm up in NYC today.—

**Comment by gregelin** [comment]
+1 to the above.

I also think we should share phone numbers of all organizers and volunteers
as backup.

Greg

**Comment by nathenharvey** [comment]
regarding sharing contact info, @xzilla is assigned #39

**Comment by markcornick** [comment]
VictorOps invites have been sent.

**Comment by markcornick** [comment]
This is ready to go, but the last thing we might want to do is create an alias for the some-long-uuid@victorops.com email address that will be more human-friendly. Any suggestions from anyone?

**Comment by gregelin** [comment]
Suggestion for email address?
doddc@victorops.com
devopsdaysdc@victorops.com

or suggestion of where to host the email alias?

Greg

**Comment by nathenharvey** [comment]
I set-up a google apps account for us.  @markcornick has admin access.  You have another email address ;)

**Comment by markcornick** [comment]
alert@devopsdaysdc.org will be our primary endpoint for incoming mail. Unfortunately, I wasn't able to get the automatic-routing (the +ROUTING_KEY) to work with Google Apps, so everything will go into the "everyone" queue which is currently me, @nathenharvey and @mbarbine. We'll reassign to the other queues as needed.
