### ISSUE TITLE
Fireeye a sponsor?

### ISSUE THREAD

**Issue by nathenharvey** [DevOpsDaysDC/planning#49]
Have they paid?

they aren't listed and don't have a discount code (yet)

**Comment by nathenharvey** [comment]
@jasonNetuitive @gallimorej has Fireeye paid as a sponsor yet?

**Comment by gallimorej** [comment]
The check is in the mail. We just haven't received payment yet.

**Comment by nathenharvey** [comment]
@radiocats @mbarbine can you send over a logo?

Once payment is received we'll get you listed on the website.

/cc @markcornick

**Comment by mbarbine** [comment]
Yes. I'll send it over shortly

**Comment by mbarbine** [comment]
![fireeye-2-color](https://cloud.githubusercontent.com/assets/3211492/7968880/615e8f64-0a01-11e5-8784-d3afb79f9f82.png)

**Comment by mbarbine** [comment]
Do we need something Hi-Res?

**Comment by markcornick** [comment]
Nope, the one you sent should work. I'll get it on the site later today.

**Comment by markcornick** [comment]
What level sponsor is FireEye?

**Comment by radiocats** [comment]
Platinum

**Comment by markcornick** [comment]
OK. Site changes are ready to go when payment is received.

**Comment by mbarbine** [comment]
Platinum

**Comment by nathenharvey** [comment]
they've paid.  /cc @markcornick

**Comment by gallimorej** [comment]
Check received 6/8
