### ISSUE TITLE
Email currently registered about refund policy

### ISSUE THREAD

**Issue by nathenharvey** [DevOpsDaysDC/planning#50]
* No refunds after 6/5
* Many on the waitlist, no hard feelings if you can't make it

**Comment by nathenharvey** [comment]
https://manage.busyconf.com/events/devopsdaysdc2015/messages/5568b087c78cf80400000064/edit

I've asked @gallimorej to review and send if it looks good.

**Comment by gallimorej** [comment]
Sent on 5/29.
