### ISSUE TITLE
Open Space supplies

### ISSUE THREAD

**Issue by nathenharvey** [DevOpsDaysDC/planning#54]

**Comment by mbarbine** [comment]
What supplies are needed? I've never been to an open spaces.

**Comment by nathenharvey** [comment]
* 4 large post-it flip chart pads
* 4x6 (or larger) post-it notes - at least 1000
* 4 packs markers - suggest [Mr. Sketch](http://www.amazon.com/Sanford-Mr-Sketch-Assorted-Markers/dp/B00006IFH0) as they work best on flipcharts and such...and smell really good :)
* 50 sharpie markers (black, blue, green, or assorted)
* 2 yard sticks

**Comment by nathenharvey** [comment]
@mbarbine can you pick up this stuff while you're shopping for speaker gifts, too?

**Comment by mbarbine** [comment]
You read my mind @nathenharvey - of course!

**Comment by mbarbine** [comment]
Will Open Spaces have tables? or do we need 4 easels for the large post-it flip chart pads.
