### ISSUE TITLE
sponsor pitch schedule

### ISSUE THREAD

**Issue by nathenharvey** [DevOpsDaysDC/planning#57]
which sponsors are giving their one-minute pitch when?

**Comment by nathenharvey** [comment]
We'll put them in the order they were paid and divide it evenly across the 4 slots.

**Comment by jasonNetuitive** [comment]
Here is the order:
Excella Consulting
Sumo Logic
Luminal
Sonatype
Ansible
Netuitive
Chef
Elastic
Red Hat
Custom Ink
Delphix
VictorOps
FireEye

The activity has been updated, please review and "accept" if it looks good.  thanks
