### ISSUE TITLE
Get videos from USPTO, post to vimeo

### ISSUE THREAD

**Issue by nathenharvey** [DevOpsDaysDC/planning#67]

**Comment by nathenharvey** [comment]
Videos from USPTO are available here:

https://www.dropbox.com/sh/j7b1hy8e58j6evi/AACZJRNJ2xf8VxJ2f_-zD3jxa?dl=0

- [ ] Split up videos into one video per talk
- [ ] Post videos to shared DevOpsDays vimeo Account
- [ ] Embed videos in main DevOpsDaysDC program page(s)

Anyone interested / available to help with this?  /cc @DevOpsDaysDC/owners

**Comment by nathenharvey** [comment]
@mbarbine I'm going to cc you on an email to someone else who volunteered to do this, too.  stand by!

**Comment by momecca** [comment]
I'm interested.  I'd like to split them and then split the audio for both a video and audio podcast format.  For the videos, I think they can reference vimeo, or youtube.  Where should the splits go?
