### ISSUE TITLE
compile photos

### ISSUE THREAD

**Issue by nathenharvey** [DevOpsDaysDC/planning#70]
a lot of photos were taken.  Let's compile them here.

**Comment by owdd** [comment]
Here are a couple that I took of you lads on stage.
![dod2](https://cloud.githubusercontent.com/assets/8418679/8239839/67298242-15cc-11e5-90bc-1030824803e9.jpeg)
![dod1](https://cloud.githubusercontent.com/assets/8418679/8239845/6a78d664-15cc-11e5-91cf-726c60533ba3.jpeg)

**Comment by nathenharvey** [comment]
I've added some pics to this folder in the repo.  Please add more!

https://github.com/DevOpsDaysDC/planning/tree/master/pics
