### ISSUE TITLE
Launch the CFP

### ISSUE THREAD

**Issue by nathenharvey** [DevOpsDaysDC/planning#71]
- [ ] Target speakers within 100 miles again
- [ ] Set an opens date and closes date under **Call for Proposals > Settings > Basics**
- [ ] Define any extra custom questions for the CFP under **Event > Custom Questions**
- [ ] Assign specific custom questions to the CFP's activity or speaker fields under **Call for Proposals > Settings > Basics**
- [ ] Add instructions, graphics, maps, etc to the CFP side pane under **Call for Proposals > Settings > Content**

**Comment by ramezjm** [comment]
CFP 2016 start date is Feb 1.
CFP end date: ?? (Last year it was April 15 2015.) I recommend April 30 that so it doesn't overlap with end of tax season :)
I'm working on getting info from last year's CFP to see what we can reuse.

**Comment by ramezjm** [comment]
@nathenharvey Can you give me access to view the CFP pages for 2015 in Busyconf?

**Comment by ramezjm** [comment]
All prep work is done for this. I kept the deadline as 4/15, to allow reviews to end by 4/30.

I also recommend we maintain the same questions for both registrants and CFP submissions (t-shirt size, first devopsdays, etc...)
