### ISSUE TITLE
Launch Sponsorships

### ISSUE THREAD

**Issue by nathenharvey** [DevOpsDaysDC/planning#73]
- [x] Define levels (same as last year?)
- [x] Create a prospectus
- [x] Create ticket types in BusyConf
- [x] Update the website
- [x] Launch sales

**Comment by jasonNetuitive** [comment]
Thanks to Nathen for updating the website.  I sent out messages to all the folks asking about sponsoring the event.  I still need to send out a note to all the past sponsors.  that will go out later today.  And now I just need to make sure everything is working correctly in busy conf.
