### ISSUE TITLE
Identify and assign facilitators for the open spaces

### ISSUE THREAD

**Issue by nathenharvey** [DevOpsDaysDC/planning#76]

**Comment by mbarbine** [comment]
Top question: What does a facilitator really do? 

@nathenharvey

**Comment by nathenharvey** [comment]
**Opening the session - Suggested Procedure**
* Introduce yourself
* Briefly explain your role as a facilitator
  * To remain neutral
  * Not to weigh in on any "official" / "expert" perspective
  * Help to bystand the conversation if the group is stuck
  * Engage other voices in the room in only a few dominate the session

**Managing the session**
* Clock management.  Sessions should start on the hour and end on the “50”
* Assign a notetaker for the session, you should not be the notetaker for the session
* Allow the community the opportunity to self police before stepping in
* Stepping in:
  * Ask critical questions as necessary to move stuck conversations
  * Ensure everyone has an equal voice at the meeting
  * Remain in a neutral position

**Tips for Facilitators**
Follow these simple steps:
1. Convene the space, and start the conversation with a re-statement of purpose. 
2. Observe others in the room, and ask direct questions of people that work with the theme of the conversation as it flows.
3. If one voice begins to dominate, acknowledge that their point of view has been understood, and move to rule 2 with another person.

**Comment by ramezjm** [comment]
It would be great to have a simple 3x5 or similar which facilitators and scribes can fill out, then turn in for some swag. That can also contain other info such as etherpad link.

**Comment by nathenharvey** [comment]
:+1:

**Comment by atkraft** [comment]
On Tuesday I discussed an interest by USPTO volunteers to provide facilitators and scribes for the open spaces with Nathen and Mike.

**Comment by nathenharvey** [comment]
I'm getting cards printed up for the spaces and the facilitators.
