### ISSUE TITLE
Create etherpads for each open space session

### ISSUE THREAD

**Issue by nathenharvey** [DevOpsDaysDC/planning#78]

**Comment by ramezjm** [comment]
I can help with this since I've managed it last year. Feel free to assign to me.

**Comment by nathenharvey** [comment]
I created a mapping of spaces-to-playing cards.  Should be an easy, fun way to identify the etherpads and the various spaces.

https://gist.github.com/nathenharvey/5a2a56e3111570f25ac373acb01ac011

**Comment by nathenharvey** [comment]
I've started some generic pads such as:

* Reading List
* We are Hiring
* Looking for Work
* Social Media
* Feedback on DevOpsDays DC
