### ISSUE TITLE
District of DevOps Report

### ISSUE THREAD

**Issue by nathenharvey** [DevOpsDaysDC/planning#81]
- organize organizers
- DevOps Report data from Nicole
- brief video updates from 2015 speakers
- collection of reports around DevOps in the District
- soundbytes from 2015 talks (for 2016 web site)

**Comment by atkraft** [comment]
I mentioned the DevOps Report to Mike Bland of GSA's 18F group.  I'll be having a more in depth discussion with Mike on Feb 1st; so we might be able to get some contributions to the report from the 18F team and the agencies that they work with.

**Comment by nathenharvey** [comment]
OBE at this point.  Maybe something we could workshop at the conference and plan for next year.
