### ISSUE TITLE
Badge Design

### ISSUE THREAD

**Issue by mbarbine** [DevOpsDaysDC/planning#85]
Any ideas on this?

Going to a few conferences my favorite badges are the ones that have a feature or something special within it that make it a keepsake.

**Comment by atkraft** [comment]
I think last year's badge with the logo & attendee name printed on both sides is a good idea worth repeating this year.  For the design, one idea would be to use last year's logo & "DevOps Days DC" with the addition of 2016 to distinguish it from last year; then come up with a new red, white, & blue stripes background.

**Comment by mbarbine** [comment]
![img_51561](https://cloud.githubusercontent.com/assets/3211492/12800757/7828de56-caa5-11e5-8ab8-f147ae4ede70.jpg)

A friend of mine mocked this up for us and said he'd be happy to make changes or if anyone else has an idea. This was the first iteration. Not bad.

**Comment by atkraft** [comment]
Yes, it looks good.

Thanks,

Alan

**Comment by nathenharvey** [comment]
This is a fun take on a new design.  The think I think it's missing though is some gears.  (Almost?) every DevOpsDays logo has some gears in it to help it stay somewhat consistent with the main DevOpsDays logo.

**Comment by mbarbine** [comment]
![devopsdays](https://cloud.githubusercontent.com/assets/3211492/13622119/8a4a5a62-e56a-11e5-8c71-5a9c26c5b1ba.jpg)

**Comment by atkraft** [comment]
I like the use of the capitol dome.  Of the three designs, I think the center one shows the "DC" most clearly in the gears.  The one on the right is second best on that issue, while some people may not see the "DC" in the gears of the one on the left.

**Comment by mbarbine** [comment]
Thanks @atkraft I'll let the designer know that we want to go with the middle one. I'll get all of the artifacts over to you asap. 

I'll get the artifacts for the other/monument logo as well.

**Comment by gallimorej** [comment]
2015 badge design
[34498_Devops-DC_proof2.pdf](https://github.com/DevOpsDaysDC/planning/files/213012/34498_Devops-DC_proof2.pdf)

**Comment by mbarbine** [comment]
teewatkins@mac.com

Thank you Terry! For helping out with this and offering your design expertise. We all appreciate it and look forward to what you come up with.  Below are the notes and some questions to consider.  

One of the most important questions is when we need to have this all worked out in time to get everything agreed on and printed? Let’s set expectations on when we want to have all of this fleshed out. I will post everything on Github.  

DevOpsDays DC Logo Notes:

•	Design less rectangular so that it can potentially be used on all applications without redesign. (fitting badge dimensions)  
•	Experiment with alternate color scheme(s)
•	Tweak gear size so that DC is more defined as well as maintaining dimensions for application (applying logo to badge, tshirt, slides, etc.) 
•	Mock up one with title on bottom of logo 
•	Mock up another with title on top of logo 
•	Keep consistency with the font (art deco font). Should be more bold. 
•	DC should be plainly visible
•	Potential ways to incorporate the existing logo(s) in a creative way while taking the overall design up a notch. 


Examples: 

DevOpsDays 
        DC
Or 
         DC
DevOpsDays 

Questions: Badges

Do we need to have the persons name on the badge? 
-	This would leave more space for a logo
-	I’ve been to many conferences where names were not on the badges. This doesn’t seem to impact networking.  
-	Registration would be easier (everyone has the same badge) 

Will the speakers/organizers have different color badges? 
-	This is common with other conferences I’ve been too. 

Questions: Tshirts

-	Do we have any general rules to follow (custom ink) that can be shared? 
o	Colors that do not work, font size, font weight, font type etc. 
-	Dimensions of tshirt logo? (front/back) 

Questions: Animation

-	There is also oppurtunity for some animation in a slide show. Do we have any need or want for this? I saw someone posted on the issues about doing something like this. 
-	Please share your ideas with everyone.

**Comment by gallimorej** [comment]
To some of the questions posed by @mbarbine:

1. I'm a fan of having the name, company, and Twitter handle on the badge. It helps me with conversations and to remember someone's name and details -- I'm a visual learner. so seeing the information is good. And it also personalizes the badge -- which makes it a keeper.

2. Voting against speaker badges different than attendee badges. Creates a "class system" within the event: special speakers and "ordinary" attendees. [Everyone is special](http://vignette3.wikia.nocookie.net/barney/images/4/45/Everyoneisspecial2005.jpg/revision/latest?cb=20150722120728)!

We probably need to have the design locked down with the badge producer by mid-May. That means having the concept and most of the design done before that so we have a little time for some back-and-forth tweaks when they put it on the badge.

**Comment by gregelin** [comment]
@mbarbine Do we have a status update on the logo?

**Comment by gregelin** [comment]
General update on badges. I've spoken with our badge company, Access Events, and received a quote based on last year. Have also provided Access Events with this year's artwork.

Access events will need final list of names by 5/30 to get us name tags by 7/6.

**Comment by clumpidy** [comment]
You mean they'd get us the tags by 6/7 (instead of 7/6)?

**Comment by gregelin** [comment]
Thanks. I meant getting the tags by 6/6. I would rather have them arrive 6/6 instead of 6/7.

**Comment by mbarbine** [comment]
That’s cutting it a bit close. Opt for expedited shipping if available. Not a lot of room for error here.






Respectfully,
Michael Barbine
Excella Consulting, Senior Consultant
Michael.Barbine@Excella.com<mailto:Michael.Barbine@Excella.com> / 540-671-1261 / excella.com

**Comment by gregelin** [comment]
We can do expedited shipping. 

The real challenge is the names Lee changing as we go into that last week. We go to early and we miss many names.

**Comment by mbarbine** [comment]
Can we leave the space where the name would go and just print off address labels to stick on?




Respectfully,
Michael Barbine
Excella Consulting, Senior Consultant
Michael.Barbine@Excella.com<mailto:Michael.Barbine@Excella.com> / 540-671-1261 / excella.com

**Comment by gregelin** [comment]
That is what we did for X number of badges last year to address last minute changes. It's just that we want to limit that number. 

But this the schedule we did last year.

**Comment by nathenharvey** [comment]
design is done.  Closing this one out.
