### ISSUE TITLE
Rolling A/V Televisions/Monitors

### ISSUE THREAD

**Issue by mbarbine** [DevOpsDaysDC/planning#89]
Does the USPTO have these avaiable for us to use? 

What is the size of the television/monitor? 

Can it be oriented vertically?

**Comment by atkraft** [comment]
I've asked for details on this from our Conference Services group.  The ones that I've seen here in the past are fixed in a horizontal mount.  They should get back to me with an answer later this week.

**Comment by atkraft** [comment]
Our Conference Services group has 2 cart mounted NEC V651 displays (65").  The specs are at this link http://www.necdisplay.com/p/large-screen-displays/v651?type=support

They also have 4 smaller 42" displays mounted on flat based pedestals (I don't have the model number for those yet)

**Comment by atkraft** [comment]
Here's the plan that was discussed yesterday with the USPTO's Conference Services team.  The two 65" displays are network connected and will stream the conference talks.  One will be located in the south most section of the cafeteria.  The other will be outside the center of the south wall of the Madison Auditorium facing the Lower Atrium, on each side of that 65” display there are 42” displays (without network connections) that will continually loop through a slide show loaded onto USB drives that contain content for the agenda, open spaces locations, sponsor info, etc.  During breaks & open spaces the 65" displays can also loop a similar slideshow.

Do we want a separate issue for the creation of the slideshow content, or should that continue in this issue?

**Comment by atkraft** [comment]
All of the monitors are fixed in a horizontal position.

**Comment by atkraft** [comment]
Opened issue #94 "Create looping content for Atrium monitors" to handle the content creation mentioned above on Mar 30.
