### ISSUE TITLE
Organizers Meeting - Friday, April 1

### ISSUE THREAD

**Issue by nathenharvey** [DevOpsDaysDC/planning#92]
Let's have an organizers meeting on Friday, April 1.

Add comments and updates to this ticket that include status updates and things you'd like to discuss at the meeting.  I'll collate all the topics and send out an agenda before the meeting.

Things I'd like to discuss include:

* Ticket sales
* Sponsors
* Location
* Food
* Social activities
* Hotel room block

**Comment by jsmartin** [comment]
Let's talk about lack of talk submissions and how we can get more.

**Comment by gallimorej** [comment]
Wish I could make it to the meeting. Here's the registration status for various group:
General Admission: 78 out of 250
Government Admission: 1 out of 50
USPTO Admission: 0 out of 30
Sponsor Admission: 4 out of 120
Media: 0 out of 5
Organizers: 10 out of [however many we need]

**Comment by xzilla** [comment]
I've noticed a few emails being forwarded from Bridget that have gone unanswered, we should chat about how to answer them.
