### ISSUE TITLE
Create looping content for Atrium monitors

### ISSUE THREAD

**Issue by atkraft** [DevOpsDaysDC/planning#94]
There will be two 42" monitors that can display looping content (agenda, sponsor logos, etc.) set up in the Atrium.  If we want, this same content can also be displayed on the 65" monitors used to livestream the keynotes during breaks and open spaces.

**Comment by atkraft** [comment]
More detail from the last planning session with the USPTO Conference Services team.

The two 65" displays are network connected and will stream the conference talks. One will be located in the south most section of the cafeteria. The other will be outside the center of the south wall of the Madison Auditorium facing the Lower Atrium, on each side of that 65” display there are 42” displays (without network connections) that will continually loop through a slide show loaded onto USB drives that contain content for the agenda, open spaces locations, sponsor info, etc. During breaks & open spaces the 65" displays can also loop a similar slideshow.

**Comment by nathenharvey** [comment]
We might consider including a word cloud of the companies attending with size relative to the number of people they're sending.  It would look something like this given current attendance.

![companies](https://cloud.githubusercontent.com/assets/16093/15624665/f722f420-245b-11e6-939f-70fb7213ff46.png)

**Comment by atkraft** [comment]
I like the idea.  Is there an easy way to keep the multi-word organizations (Justice Department, Sauce Labs, etc) from being split?  If not, no worries; but it does make the one word organizations more recognizable than the multi-word orgs.

**Comment by nathenharvey** [comment]
What should be included:

* Sponsor thank you slides
* Daily schedule
* Map of the venue
* Happy Hour information
* Companies attending (without breaking up multi-word company names)

**Comment by nathenharvey** [comment]
https://github.com/DevOpsDaysDC/planning/blob/master/2016-slides/rotating_slides.pptx

**Comment by atkraft** [comment]
Looks great; a couple of excellent ideas to carry forward into future events; credit for the logo designer, staff & volunteer T-shirt colors, and splitting the schedules into AM  & PM (more digestible than a whole day).
