### ISSUE TITLE
Register for Speaker/Sponsor dinner

### ISSUE THREAD

**Issue by nathenharvey** [DevOpsDaysDC/planning#96]
- [x] Set-up busyconf ticket and proper custom questions
- [x] email the speakers asking them to register
- [x] email the sponsors asking them to register
- [x] tell organizers to register
- [x] send list to Trademark.

**Comment by nathenharvey** [comment]
Ticket is set-up.  Discount code to display the ticket has been shared with @ramezjm and organizers in slack.

**Comment by nathenharvey** [comment]
I'm working on sponsor notifications.

**Comment by nathenharvey** [comment]
sponsors and organizers have all been asked to register.

**Comment by ramezjm** [comment]
Speakers have been emailed with a request and instructions to register.

**Comment by nathenharvey** [comment]
33 people registered as of 27 May.

**Comment by nathenharvey** [comment]
Need to remind folks to register and get a list of who's missing.

**Comment by nathenharvey** [comment]
reminders sent to everyone.  We are now at 42 registrants.
