### ISSUE TITLE
Speaker Gifts

### ISSUE THREAD

**Issue by nathenharvey** [DevOpsDaysDC/planning#99]
- [x] Purchase tumblers
- [x] Chocolates?
- [x] Speaker ready kit?  water, hand sanitizer, kleneex, etc.
- [x] distribution method

**Comment by nathenharvey** [comment]
Tubmlers ordered

**Comment by nathenharvey** [comment]
[chocolates to order](http://www.gearhartschocolates.com/collections/assortments/products/16-piece-gift-assortment)

**Comment by mbarbine** [comment]
![speaker-ready-item-list-part2](https://cloud.githubusercontent.com/assets/3211492/15679128/bc5dd448-271e-11e6-97ad-9ae3c93b4573.png)
![speaker-ready-item-list-part3](https://cloud.githubusercontent.com/assets/3211492/15679127/bc571f04-271e-11e6-8f9e-585e1ff0fac1.png)
![speaker-ready-item-list-1](https://cloud.githubusercontent.com/assets/3211492/15679126/bc482832-271e-11e6-8d42-b5d7e2282545.png)

**Comment by nathenharvey** [comment]
@mbarbine is that your order from last year?

**Comment by mbarbine** [comment]
Anything we want to add to this? The picture/comments above is the order I placed last year and I will get the bags put together, we can put the chocolates in on Tuesday evening. 

Anything we should add? 

The quantities are not updated, but # of speakers + # of organizers is what we did last year. I can figure that out.

**Comment by mbarbine** [comment]
![speaker-ready-item-list-part3](https://cloud.githubusercontent.com/assets/3211492/15679212/07ec37a6-271f-11e6-90c0-d149191a9692.png)

**Comment by mbarbine** [comment]
do we want to have these for volunteers as well?

**Comment by mbarbine** [comment]
@nathenharvey distribution method should be done at registration since some speakers may not be at the dinner. Since I won't be around on Tuesday. I will drop them off at the Westin/Trademark on Monday.

**Comment by nathenharvey** [comment]
I don't think we need the easels.  Can you add some [painter's tape](http://www.amazon.com/Duck-240180-Release-Painters-Inches/dp/B0054P49YE/ref=sr_1_2?s=industrial&ie=UTF8&qid=1464707093&sr=1-2)?

40 bags should be a sufficient number.

@mbarbine let me know if you order or if you'd like me to.  I'm happy to have it shipped to you but paid for directly from our account or can just reimburse you for what you spend.

**Comment by mbarbine** [comment]
Ordered. I sent you @nathenharvey the total... paypal works. I didn't see your comment until just now. Everything should be here tomorrow.
